name: dependencies
on: pull_request

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create/Update Changesets
        uses: 'the-guild-org/changesets-dependencies-action@v1.0.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
